### ISSUE TITLE
Error in data generation 

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [hpi-epic/manm-cs#35]
I receive the following error when generating a dataset with 50 nodes. Worked for 25 nodes.

mpci-dag/src/variables/discrete_variable.py:32: RuntimeWarning: overflow encountered in exp
  e_sum = np.sum([np.exp(k*value) for  k in categories])
mpci-dag/src/variables/discrete_variable.py:33: RuntimeWarning: overflow encountered in exp
  softmax = [np.exp(k*value) / e_sum for  k in categories]
mpci-dag/src/variables/discrete_variable.py:33: RuntimeWarning: invalid value encountered in double_scalars
  softmax = [np.exp(k*value) / e_sum for  k in categories]
mpci-dag/src/variables/discrete_variable.py:32: RuntimeWarning: overflow encountered in exp
  e_sum = np.sum([np.exp(k*value) for  k in categories])
mpci-dag/src/variables/discrete_variable.py:33: RuntimeWarning: overflow encountered in exp
  softmax = [np.exp(k*value) / e_sum for  k in categories]
mpci-dag/src/variables/discrete_variable.py:33: RuntimeWarning: invalid value encountered in double_scalars
  softmax = [np.exp(k*value) / e_sum for  k in categories]
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "mpci-dag/venv/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "mpci-dag/venv/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "mpci-dag/venv/lib/python3.8/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "mpci-dag/src/graph/graph.py", line 33, in fn
    df[variable.idx] = variable.sample(df=df, num_observations=chunk_size)
  File "mpci-dag/src/variables/discrete_variable.py", line 71, in sample
    signal = self.get_non_root_signal(df=df)
  File "mpci-dag/src/variables/discrete_variable.py", line 49, in get_non_root_signal
    continuous_signal = df[continuous_parent_idxs].apply(self.logit_mapper_func, axis=1) \
  File "mpci-dag/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 7552, in apply
    return op.get_result()
  File "mpci-dag/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "mpci-dag/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "mpci-dag/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 305, in apply_series_generator
    results[i] = self.f(v)
  File "mpci-dag/src/variables/discrete_variable.py", line 42, in func
    return np.sum([np.where(np.random.multinomial(1,self.mult_logit_function(value=value)) == 1)[0][0] for  value in parent_values])
  File "mpci-dag/src/variables/discrete_variable.py", line 42, in <listcomp>
    return np.sum([np.where(np.random.multinomial(1,self.mult_logit_function(value=value)) == 1)[0][0] for  value in parent_values])
  File "mtrand.pyx", line 4212, in numpy.random.mtrand.RandomState.multinomial
  File "_common.pyx", line 338, in numpy.random._common.check_array_constraint
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs

**Comment by ChristopherSchmidt89** [comment]
`    def mult_logit_function(self, value) -> pd.Series:
        categories =  list(range(1, self.num_values))`
        
Not fixing the bug, but shouldn't categories be of `range(1,self.num_values + 1)` or  `range(0, self.num_values)` currently if we have for example num_values == 2 (i.e., 2 categories for the discrete variable) we get the local variable categories with a list of 1 element, i.e.
` list(range(1,2))
[1]`
